apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app: django-app
spec:
  schedule: "0 0 * * *"
  jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name : django-container
                image: django-app
                command: ['./manage.py', 'clearsessions']
                envFrom:
                  - configMapRef:
                      name: django-config
                imagePullPolicy: Never
            restartPolicy: OnFailure