apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app: django-app
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name : django-container
          image: django-app
          command: ['./manage.py', 'migrate', '--no-input']
          envFrom:
            - configMapRef:
                name: django-config
          imagePullPolicy: Never
      restartPolicy: OnFailure